### Listar itens
GET http://localhost:3001/item/

### Buscar itens por carrinho
GET http://localhost:3001/item/3c7fd675-5d11-43bb-8568-31e8e67ef36b

### Adicionar item ao carrinho
POST http://localhost:3001/item/2/123/3c7fd675-5d11-43bb-8568-31e8e67ef36b
